name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Nix and Rust Environment
        uses: ./.github/actions/setup-nix-rust

      - name: Run cargo fmt
        run: nix develop --command cargo fmt --all -- --check

      - name: Run cargo clippy
        run: nix develop --command cargo clippy --all-targets --all-features -- -D warnings

      - name: Run cargo test
        run: nix develop --command cargo test --verbose

  # benchmark:
  #   name: Bench
  #   runs-on: ubuntu-latest
  #   needs:
  #     - check
  #   steps:
  #     - name: Checkout sources
  #       uses: actions/checkout@v4
  #
  #     - name: Setup Nix and Rust Environment
  #       uses: ./.github/actions/setup-nix-rust
  #
  #     - name: Run benchmark
  #       run: nix develop --command cargo bench | tee output.txt
  #
  #     - name: Store benchmark result
  #       uses: benchmark-action/github-action-benchmark@v1
  #       with:
  #         name: Rust Benchmark
  #         tool: "cargo"
  #         output-file-path: output.txt
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         auto-push: true
  #         alert-threshold: "110%"
  #         comment-on-alert: true
  #         fail-on-alert: true
  #         alert-comment-cc-users: "@andyyu2004"
